#!/bin/bash
rm -rf build
mkdir build
cd build
cmake \
    -DPICO_SDK_PATH=/home/iot/raspberry-pi-pico/pico/pico-sdk/ \
    -DPICO_EXTRAS_PATH=/home/iot/raspberry-pi-pico/pico/pico-extras/ \
    -DPICO_ENC28J60_PATH=/home/iot/raspberry-pi-pico/pico/pico-enc28j60/ \
    ..

make